// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/wedding.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WeddingService_CreateWedding_FullMethodName = "/wedding.WeddingService/CreateWedding"
)

// WeddingServiceClient is the client API for WeddingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeddingServiceClient interface {
	CreateWedding(ctx context.Context, in *Wedding, opts ...grpc.CallOption) (*Wedding, error)
}

type weddingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeddingServiceClient(cc grpc.ClientConnInterface) WeddingServiceClient {
	return &weddingServiceClient{cc}
}

func (c *weddingServiceClient) CreateWedding(ctx context.Context, in *Wedding, opts ...grpc.CallOption) (*Wedding, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Wedding)
	err := c.cc.Invoke(ctx, WeddingService_CreateWedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeddingServiceServer is the server API for WeddingService service.
// All implementations must embed UnimplementedWeddingServiceServer
// for forward compatibility.
type WeddingServiceServer interface {
	CreateWedding(context.Context, *Wedding) (*Wedding, error)
	mustEmbedUnimplementedWeddingServiceServer()
}

// UnimplementedWeddingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeddingServiceServer struct{}

func (UnimplementedWeddingServiceServer) CreateWedding(context.Context, *Wedding) (*Wedding, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWedding not implemented")
}
func (UnimplementedWeddingServiceServer) mustEmbedUnimplementedWeddingServiceServer() {}
func (UnimplementedWeddingServiceServer) testEmbeddedByValue()                        {}

// UnsafeWeddingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeddingServiceServer will
// result in compilation errors.
type UnsafeWeddingServiceServer interface {
	mustEmbedUnimplementedWeddingServiceServer()
}

func RegisterWeddingServiceServer(s grpc.ServiceRegistrar, srv WeddingServiceServer) {
	// If the following call pancis, it indicates UnimplementedWeddingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeddingService_ServiceDesc, srv)
}

func _WeddingService_CreateWedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Wedding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeddingServiceServer).CreateWedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeddingService_CreateWedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeddingServiceServer).CreateWedding(ctx, req.(*Wedding))
	}
	return interceptor(ctx, in, info, handler)
}

// WeddingService_ServiceDesc is the grpc.ServiceDesc for WeddingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeddingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wedding.WeddingService",
	HandlerType: (*WeddingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWedding",
			Handler:    _WeddingService_CreateWedding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/wedding.proto",
}
